ROLE_ADMIN = "admin"
ROLE_MENTOR = "mentor"
ROLE_ACADEMIC = "academic"
ROLE_STUDENT = "student"

ROLE_VALUES = {ROLE_ADMIN, ROLE_MENTOR, ROLE_ACADEMIC, ROLE_STUDENT}

THESIS_STATUS_DRAFT_SUBMITTED = "draft_submitted"
THESIS_STATUS_ANALYSIS_PENDING = "analysis_pending"
THESIS_STATUS_ANALYSIS_DONE = "analysis_done"
THESIS_STATUS_MENTOR_REVIEW = "mentor_review"
THESIS_STATUS_CHANGES_REQUESTED = "changes_requested"
THESIS_STATUS_APPROVED = "approved"
THESIS_STATUS_FINAL = "final"

ANALYSIS_STATUS_PENDING = "pending"
ANALYSIS_STATUS_RUNNING = "running"
ANALYSIS_STATUS_COMPLETED = "completed"
ANALYSIS_STATUS_FAILED = "failed"

VERSION_STAGE_DRAFT = "draft"
VERSION_STAGE_REVISION = "revision"
VERSION_STAGE_FINAL = "final"

ALLOWED_UPLOAD_EXTENSIONS = {".pdf"}
